### ISSUE TITLE
CLI: On new machine, present instructions for installing sources 

### ISSUE THREAD

**Issue by rphovley** [CodeClimbersIO/cli#114]
When a user first installs codeclimbers, they will have no data and no sources. Present the add sources modal so they know how to get started

**Comment by Tanner-Scadden** [comment]
I wonder if there should be a landing page if the account doesn't have any sources, where it just goes over how to add one, and transitions to the home page as soon as it gets a pulse from one?

**Comment by rphovley** [comment]
Rather than a different page, maybe the "empty" state for the components directs the users to the sources. Like the time widget empty state is just a button with some text that says "To start tracking your time, add a source"

**Comment by Tanner-Scadden** [comment]
I like that too. 

Another idea I have is to use the animation we want to do for deep work timers, and outline the add source button with it when there's no sources to really drive your attention there

**Comment by rphovley** [comment]
Ooo, that's a nice way to do it. That's probably best of all these ideas because it teaches the user how to add sources the way they will always add sources

**Comment by Tanner-Scadden** [comment]
Fixed in https://github.com/CodeClimbersIO/cli/pull/145
