### ISSUE TITLE
CLI: Fields for some important columns come in blank for activity records

### ISSUE THREAD

**Issue by rphovley** [CodeClimbersIO/cli#120]
language, machine, editor, and operating system are coming in blank. These fields are calculated based on other fields. machine and operating system should likely come off of the user_agent fields, or be present in the request headers. 

lnaguage and editor should be available based on which application is bringing in the activity. This should also be able to be derived from the user agent and the entity field (and the extension of the file)

**Comment by Tanner-Scadden** [comment]
Addressed in the browser extension in https://github.com/CodeClimbersIO/browser-extension/pull/27

**Comment by Tanner-Scadden** [comment]
We need to update https://github.com/CodeClimbersIO/vscode-climbers/blob/55d5388c708ddd3b164d4d29697b7152691f1fe1/src/wakatime.ts#L538 needs to be updated to send 
```editor: vscode``` and the user's language in vscode if we don't want it to come from the CLI. 

Might have to wait for this ticket though?
https://github.com/CodeClimbersIO/vscode-climbers/issues/2

**Comment by rphovley** [comment]
I think we want to handle this on the CLI side so we can support other wakatime extensions we haven't supported. The user-agent string contains the editor being used. I think the logic would be something like, if the `type`: is file, the editor is assigned from the user-agent string, otherwise it remains blank for other `types` of heartbeats
