### ISSUE TITLE
npm run lint may require npm run build first 

### ISSUE THREAD

**Issue by rphovley** [CodeClimbersIO/cli#22]
One of the rules in eslint we are currently using is import/no-unresolved. This causes the project to fail to meet the pr check for linting.

The start command in src/commands/start requires the use of the server module. This module is not created until the build for the project is generated. 

Two potential options:
1) update the workflow to run a npm run build first before executing npm run lint
2) add an ignore to the file

Please investigate the issue. Open to other solutions

**Comment by Idrinth** [comment]
Building seems to be too much of an overhead for this single line time-wise, I'll add an ignore.
