### ISSUE TITLE
npx codeclimbers start

### ISSUE THREAD

**Issue by BeratDen** [CodeClimbersIO/cli#266]
It seems the server is having trouble starting. Run the command
 
 Getting latest 50 lines of error logs...
npm warn exec The following package was not found and will be installed: codeclimbers@0.3.13
npm warn deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated npmlog@6.0.2: This package is no longer supported.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm warn deprecated gauge@4.0.4: This package is no longer supported.

node -v v20.16.0

**Comment by rphovley** [comment]
@BeratDen thanks for sharing. Is this on a windows device? Does the cli output look something like?

![image](https://github.com/user-attachments/assets/1ed73258-9949-487d-8b1a-ae4ecd792948)

**Comment by BeratDen** [comment]
Cli throw the error on first boot, even for the error server started perfectly fine
![Ekran görüntüsü 2024-11-16 015412](https://github.com/user-attachments/assets/1d9d937a-bfcf-434c-9cdc-ce0f19938087)

device :
Windows 11 Home Single Language
v: 23H2

**Comment by rphovley** [comment]
This is a known issue on Windows devices. Thank you for submitting this as a bug. I won't be able to solve Windows issues for a while, but the goal will be to get windows support back up

**Comment by rphovley** [comment]
Hi @BeratDen, this should be resolved with the latest release. You may have to get the service disabled and then start it back up in order for it to use the new version. 

```
npx codeclimbers startup:disable
npx codeclimbers@0.3.14 start
```

**Comment by BeratDen** [comment]
> Hi @BeratDen, this should be resolved with the latest release. You may have to get the service disabled and then start it back up in order for it to use the new version.
> 
> ```
> npx codeclimbers startup:disable
> npx codeclimbers@0.3.14 start
> ```

thenk you i will try now
