### ISSUE TITLE
CLI: configure hostfile on start

### ISSUE THREAD

**Issue by rphovley** [CodeClimbersIO/cli#35]
We want for a user to be able to view their data by going to codeclimbers.local

Add an entry to their hostfile, if it doesn't already exist, when the user runs codeclimbers start, that adds the entry to point codeclimbers.local to localhost:14400

**Comment by Idrinth** [comment]
This will require administrator access to their machines, may look a bit odd.

**Comment by rphovley** [comment]
That is true. Perhaps this is something we suggest through the CLI on first start?

**Comment by Tanner-Scadden** [comment]
Are there plans to have an initialize script made? If so, you could require it to be ran as an admin and do it then.
