### ISSUE TITLE
Adjust environment variables to start with CODECLIMBERS_ ?

### ISSUE THREAD

**Issue by Idrinth** [CodeClimbersIO/cli#42]
Currently we are using environment variables with very common names, possibly leading to collisions.

To prevent us from using a variable of a different service, please rename the ones we use to begin with `CODECLIMBERS_`, so for example `CODECLIMBERS_PORT` instead of `PORT`. In the long run we'll save a lot of time on support requests this way.

@rphovley maybe it would make sense to also have the project part in the ENV name? `CODECLIMBERS_SERVER_PORT` would then not collide with the websocket port for example.

**Comment by rphovley** [comment]
Good idea. I'll get a PR up this weekend with that

**Comment by Tanner-Scadden** [comment]
I would also suggest having a way of accessing env variables safely and parsing them on start-up to ensure they are all there.
