### ISSUE TITLE
Add testing scaffolding for database queries

### ISSUE THREAD

**Issue by rphovley** [CodeClimbersIO/cli#44]
Usually, I'm not keen on testing queries, but in this case where most of the value of our product lies in the insights/reports we provide, we need to have some scaffolding in place to be able to seed a mock dataset and test our queries against that dataset. Fortunately, the database we are using is sqlite so an in memory database makes even more sense here. 

Requirements:
- Run from a separate command from our unit tests
- spins up a new database/migrations each set of tests, our database is small rn so no need to optimize for time yet. 
- database is cleared and reseeded at the start of each test suite (not each test)

**Comment by Tanner-Scadden** [comment]
@rphovley We should reopen this. My solution wasn't truly in memory. I still need to figure out how to make it while working with the module setup. In memory wants a singular connection which is making it a little bit harder with how we have our app setup.

**Comment by rphovley** [comment]
It's not a huge deal if it's not in memory. We can ignore the file in git and be good with that if it's going to require a lot of extra work

**Comment by Tanner-Scadden** [comment]
I'll play around with it some more, but if I can't figure it out after another hour or so I think that might be best.
