### ISSUE TITLE
CLI: Configure to be able to run on bootup for Linux

### ISSUE THREAD

**Issue by rphovley** [CodeClimbersIO/cli#72]
Copy #48 for mac implementation.

When the user runs npx codeclimbers start, the application runs and establishes itself as a bootup application.
Add command npx codeclimbers startup disable to remove from bootup

**Comment by Tanner-Scadden** [comment]
@rphovley if no one wants to pick up this ticket by end of the week, I can grab my linux laptop and get this wired up.
