### ISSUE TITLE
Feature: Add Browser Pulses Support

### ISSUE THREAD

**Issue by Tanner-Scadden** [CodeClimbersIO/cli#87]
With the browser extension, we need to add support for chrome/edge/firefox! Some of the rows from my export:

<img width="1161" alt="Screenshot 2024-08-04 at 10 03 56 PM" src="https://github.com/user-attachments/assets/56d076f1-9df0-4c19-a55f-3cad8281208f">

**Comment by rphovley** [comment]
Good find! Yeah, there's definitely a lot of room for improvement with the existing extension around how it collects the data. The <<LAST_PROJECT>> is supposed to get the project from whatever coding heartbeats came in last but clearly that isn't functional haha

**Comment by Tanner-Scadden** [comment]
>> The <<LastProject>> is supposed to get the project from what ever coding heartbeats came in last 

Looks like it is grabbed [here](https://github.com/CodeClimbersIO/browser-extension/blob/5d36b036e64651062a89b8523dea6760c6b4948e/src/utils/index.ts#L24). Imo this should be driven from the current deep work session and be used a FK to aggregate the data by project easily?

**Comment by Tanner-Scadden** [comment]
Broke out to https://github.com/CodeClimbersIO/cli/issues/91
