### ISSUE TITLE
CLI: Deep Work

### ISSUE THREAD

**Issue by danzjamz** [CodeClimbersIO/cli#89]

**Comment by Tanner-Scadden** [comment]
@danzjamz Is there anything I can do to help with this? It's gonna be sick

**Comment by rphovley** [comment]
Requirements from our thread:

<img width="465" alt="Screenshot 2024-08-13 at 7 34 56 PM" src="https://github.com/user-attachments/assets/767207eb-9e12-41e8-9c63-1066822e995f">

-Example calculation https://docs.google.com/spreadsheets/d/10U2GtfVIjFEvgCT6VYp2UIkAOwazjv9m879QjPMb-tI/edit?gid=0#gid=0
